import os

dict_content = """window.i18nDictionary = {
    fr: {
        "cs.title": "DJANGOU - Bientôt Disponible",
        "cs.h1_1": "L'application est ",
        "cs.h1_2": "bientôt là.",
        "cs.desc": "L'équipe DJANGOU prépare le déploiement officiel de l'application. La révolution EdTech commence dans :",
        "cs.days": "Jours",
        "cs.hours": "Heures",
        "cs.minutes": "Minutes",
        "cs.seconds": "Secondes",
        "cs.waitlist.title": "Rejoignez la liste d'attente",
        "cs.waitlist.desc": "Soyez le premier averti lors du lancement officiel et aidez-nous à dimensionner l'application pour votre arrivée.",
        "cs.placeholder.name": "Votre nom complet",
        "cs.placeholder.email": "Votre adresse e-mail",
        "cs.role.default": "Quel est votre profil ?",
        "cs.role.dir": "Directeur / Fondateur d'établissement",
        "cs.role.prof": "Enseignant / Professeur",
        "cs.role.admin": "Personnel Administratif",
        "cs.role.parent": "Parent d'élève / Élève",
        "cs.role.other": "Autre",
        "cs.size.default": "Taille de l'établissement (Optionnel)",
        "cs.size.100": "Moins de 100 élèves",
        "cs.size.100_500": "De 100 à 500 élèves",
        "cs.size.500": "Plus de 500 élèves",
        "cs.size.na": "Je ne sais pas / Non applicable",
        "cs.btn.submit": "M'avertir du lancement",
        "cs.privacy": "Vos données serviront uniquement pour la planification du lancement.",
        "cs.back": "← Retour à l'accueil",
        "cs.modal.title": "Merci pour votre temps et intérêt pour notre projet !",
        "cs.modal.desc": "Votre inscription à la liste d'attente a bien été prise en compte. Nous vous contacterons dès le lancement officiel de DJANGOU.",
        "cs.modal.close": "Fermer",
        "cs.js.sending": "Envoi en cours...",
        "cs.js.error": "Une erreur s'est produite. Veuillez réessayer.",
        "cs.js.conn_error": "Erreur de connexion. Veuillez vérifier votre internet.",
        "cs.js.redirect": "Déploiement en cours... Redirection...",

        "idx.title": "DJANGOU - Logiciel de gestion scolaire",
        "idx.nav.feat": "Fonctionnalités",
        "idx.nav.offline": "Hors-ligne",
        "idx.nav.faq": "FAQ",
        "idx.nav.contact": "Contact",
        "idx.aria.theme": "Basculer le thème",
        "idx.nav.cta": "Accéder à DJANGOU",

        "idx.hero.eyebrow": "La plateforme EdTech adaptée à votre réalité",
        "idx.hero.hidden": "Logiciel de gestion scolaire intelligent et hors-ligne.",
        "idx.hero.desc": "DJANGOU automatise la saisie des notes, la correction et la génération des bulletins scolaires. Une application performante pensée pour les enseignants et directeurs qui veulent gagner du temps.",
        "idx.hero.cta1": "Découvrir DJANGOU",
        "idx.hero.cta2": "Voir le fonctionnement",
        "idx.hero.chip1": "IA en temps réel",
        "idx.hero.chip2": "100% Hors-ligne",

        "idx.feat.h2": "Moins de saisie manuelle. Plus de temps pour enseigner.",
        "idx.feat.desc": "Découvrez comment nos fonctionnalités repensent le travail administratif scolaire pour éliminer les tâches répétitives et chronophages.",
        "idx.feat.1.h3": "Offline-First",
        "idx.feat.1.p": "Continuez à travailler normalement même lorsque la connexion internet est coupée. Synchronisation automatique au retour du réseau.",
        "idx.feat.2.h3": "Dictée Vocale Intelligente",
        "idx.feat.2.p": "Énoncez vos notes à voix haute. L'IA les comprend et remplit automatiquement le tableau des élèves depuis votre téléphone.",
        "idx.feat.3.h3": "Scan et OCR par IA",
        "idx.feat.3.p": "Photographiez les documents ou copies compatibles. L'IA extrait automatiquement les informations pour réduire la saisie manuelle.",
        "idx.feat.4.h3": "Barèmes Automatisés",
        "idx.feat.4.p": "L'IA vous assiste pour structurer des critères de correction, facilitant le calcul automatique et rapide des moyennes globales.",
        "idx.feat.5.h3": "Bulletins PDF en masse",
        "idx.feat.5.p": "Générez instantanément des bulletins scolaires professionnels au format PDF pour l'ensemble d'une classe en un seul clic.",
        "idx.feat.6.h3": "Procès-Verbaux Excel",
        "idx.feat.6.p": "Exportez facilement les relevés complets et procès-verbaux au format Excel pour les réunions d'administration.",

        "idx.ia.eyebrow": "Intelligence Artificielle",
        "idx.ia.h2": "Dictée vocale : l'IA au service de votre productivité.",
        "idx.ia.desc": "Saisissez vos notes beaucoup plus rapidement, même depuis un smartphone. Activez le micro, énoncez la note de l'élève, et DJANGOU s'occupe de l'associer à la bonne ligne dans votre classeur numérique.",
        "idx.ia.li1": "Réduit le risque d'erreur de saisie manuelle.",
        "idx.ia.li2": "Extrêmement pratique depuis un écran de smartphone.",
        "idx.ia.demo.voice": "« Martin, 15 sur 20 »",
        "idx.ia.th1": "Élève",
        "idx.ia.th2": "Devoir 1",
        "idx.ia.th3": "Statut",
        "idx.ia.td.saisi": "Saisi",
        "idx.ia.td.voice": "Ajouté par voix",
        "idx.ia.td.waiting": "En attente",

        "idx.ocr.eyebrow": "Vision par Ordinateur",
        "idx.ocr.h2": "Scan et OCR : Digitalisez en un clic.",
        "idx.ocr.desc": "Photographiez les documents ou copies compatibles. L'IA extrait automatiquement les informations pour réduire la saisie manuelle. Un gain de temps inestimable pour le traitement des fiches papier.",
        "idx.ocr.li1": "Fini la double saisie des listes d'élèves.",
        "idx.ocr.li2": "Reconnaissance d'écriture optimisée.",
        "idx.ocr.success": "Extraction réussie",

        "idx.off.eyebrow": "Résilience réseau",
        "idx.off.h2": "L'approche Offline-First.",
        "idx.off.desc": "Dans les environnements où la connexion est lente, instable ou coûteuse, DJANGOU garantit la continuité de votre travail. Vos données récentes sont stockées localement.",
        "idx.off.badge1": "Hors-ligne",
        "idx.off.badge2": "Reconnecté",
        "idx.off.step1": "1. Vous travaillez",
        "idx.off.step1_p": "Vous saisissez les notes normalement.",
        "idx.off.step2": "2. Coupure réseau",
        "idx.off.step2_p": "L'application continue de fonctionner.",
        "idx.off.step3": "3. Synchronisation",
        "idx.off.step3_p": "Retour en ligne : envoi automatique au serveur.",

        "idx.qui.h2": "Une plateforme, deux usages complémentaires.",
        "idx.qui.ens.h3": "Pour les enseignants",
        "idx.qui.ens.p": "Fini les calculs manuels interminables et la double saisie papier-ordinateur.",
        "idx.qui.ens.l1": "Moins de saisie grâce à la voix",
        "idx.qui.ens.l2": "Calcul automatique des moyennes",
        "idx.qui.ens.l3": "Travail possible depuis le téléphone",
        "idx.qui.adm.h3": "Pour l'administration",
        "idx.qui.adm.p": "Centralisez les données de l'établissement et générez les documents officiels instantanément.",
        "idx.qui.adm.l1": "Vue globale sur les classes",
        "idx.qui.adm.l2": "Génération de bulletins PDF",
        "idx.qui.adm.l3": "Export de Procès-Verbaux Excel",

        "idx.sec.eyebrow": "Sécurité & Confiance",
        "idx.sec.h2": "Une architecture pensée pour la protection de vos données scolaires.",
        "idx.sec.1.h3": "Infrastructure Cloudflare",
        "idx.sec.1.p": "Protection active du réseau contre les attaques courantes et surveillance continue.",
        "idx.sec.2.h3": "Authentification Moderne",
        "idx.sec.2.p": "Intégration de technologies sécurisées telles que les Passkeys pour protéger les comptes.",
        "idx.sec.3.h3": "Synchronisation Sécurisée",
        "idx.sec.3.p": "Transfert maîtrisé des données de l'application hors-ligne vers nos serveurs centraux.",

        "idx.stat.1": "Enseignants actifs",
        "idx.stat.2": "Établissements partenaires",
        "idx.stat.3": "Taux de satisfaction",
        "idx.stat.4": "Temps gagné sur la saisie",

        "idx.comp.eyebrow": "Transformation",
        "idx.comp.h2": "Avant vs Après DJANGOU",
        "idx.comp.p": "Voyez concrètement ce que DJANGOU change dans votre quotidien d'enseignant.",
        "idx.comp.sans": "Sans DJANGOU",
        "idx.comp.sans.1": "Saisie manuelle note par note sur papier",
        "idx.comp.sans.2": "Calcul des moyennes à la main ou sous Excel",
        "idx.comp.sans.3": "Bulletins créés un par un en heures",
        "idx.comp.sans.4": "Perte de travail si la connexion coupe",
        "idx.comp.sans.5": "Documents éparpillés sur plusieurs fichiers",
        "idx.comp.sans.6": "Risque d'erreurs de calcul fréquent",
        "idx.comp.avec": "Avec DJANGOU",
        "idx.comp.avec.1": "Notes saisies à la voix en quelques secondes",
        "idx.comp.avec.2": "Calculs automatiques et instantanés",
        "idx.comp.avec.3": "Bulletins PDF générés en un clic",
        "idx.comp.avec.4": "Travail continu même hors connexion",
        "idx.comp.avec.5": "Tout centralisé sur une seule plateforme",
        "idx.comp.avec.6": "Aucune erreur de calcul possible",

        "idx.faq.h2": "Questions fréquentes",
        "idx.faq.desc": "Tout ce que vous devez savoir pour bien comprendre le fonctionnement de DJANGOU.",
        "idx.faq.1.q": "Qu'est-ce que DJANGOU ?",
        "idx.faq.1.a": "DJANGOU est une plateforme technologique dédiée au monde éducatif (EdTech). Elle est conçue pour aider les enseignants, directeurs et personnels administratifs à gérer plus rapidement et plus efficacement les élèves, les notes, les évaluations et la génération de bulletins.",
        "idx.faq.2.q": "DJANGOU fonctionne-t-il sans Internet ?",
        "idx.faq.2.a": "Oui. DJANGOU repose sur une architecture 'Offline-First'. Cela signifie que l'application est pensée pour continuer à fonctionner de manière transparente lors de coupures réseau. Les données saisies sont stockées localement sur votre appareil puis synchronisées en arrière-plan lorsque la connexion revient.",
        "idx.faq.3.q": "Comment fonctionne la saisie vocale ?",
        "idx.faq.3.a": "L'application utilise l'Intelligence Artificielle pour analyser votre voix. En prononçant simplement 'Martin, 15 sur 20', le système identifie l'élève et la note correspondante, puis remplit le tableau automatiquement, réduisant ainsi la saisie manuelle.",
        "idx.faq.4.q": "Comment fonctionne le scan par IA ?",
        "idx.faq.4.a": "En prenant en photo des documents ou copies compatibles, notre technologie d'OCR (Reconnaissance Optique de Caractères) assistée par IA extrait les textes et les chiffres pertinents pour les transformer en données numériques exploitables par la plateforme.",
        "idx.faq.5.q": "DJANGOU peut-il générer des bulletins ?",
        "idx.faq.5.a": "Oui. Une fois les notes et barèmes enregistrés, le personnel autorisé peut générer automatiquement des bulletins scolaires au format PDF, prêts à être imprimés ou envoyés, ainsi que des procès-verbaux globaux au format Excel.",
        "idx.faq.6.q": "Peut-on utiliser DJANGOU sur téléphone ?",
        "idx.faq.6.a": "Absolument. En tant que PWA (Progressive Web App), DJANGOU est optimisée pour s'adapter parfaitement aux écrans tactiles des smartphones, même ceux d'entrée de gamme, offrant une expérience fluide sans nécessiter de téléchargement lourd.",
        "idx.faq.7.q": "DJANGOU est-il adapté aux établissements scolaires ?",
        "idx.faq.7.a": "Oui, DJANGOU est pensé autant pour les enseignants individuels que pour l'administration globale d'un établissement. Les directeurs bénéficient d'outils de centralisation et de suivi des données scolaires.",
        "idx.faq.8.q": "Comment commencer avec DJANGOU ?",
        "idx.faq.8.a": "Cliquez simplement sur l'un des boutons 'Accéder à DJANGOU' sur cette page. Vous serez redirigé vers l'application principale où vous pourrez créer votre compte et configurer vos classes.",

        "idx.test.eyebrow": "Ils nous font confiance",
        "idx.test.h2": "Adopté par des établissements innovants",
        "idx.test.desc": "Découvrez prochainement les retours d'expérience des écoles partenaires qui ont transformé leur gestion administrative avec DJANGOU.",
        "idx.test.1.p": "« Emplacement réservé pour le futur témoignage d'un directeur d'établissement détaillant le temps gagné chaque trimestre. »",
        "idx.test.1.h4": "Directeur, Établissement Partenaire",
        "idx.test.2.p": "« Emplacement réservé pour l'avis d'un enseignant sur l'efficacité de la dictée vocale et la facilité de prise en main. »",
        "idx.test.2.h4": "Enseignant Principal",

        "idx.contact.eyebrow": "Contactez-nous",
        "idx.contact.h2": "Une question ? Parlons-en.",
        "idx.contact.desc": "Notre équipe est disponible pour répondre à toutes vos questions sur DJANGOU.",
        "idx.contact.disp.h4": "Disponibilité",
        "idx.contact.disp.p": "Lun – Ven, 8h – 18h (WAT)",
        "idx.contact.badge": "Réponse généralement sous 24h",
        "idx.contact.form.name": "Nom complet",
        "idx.contact.form.name_ph": "Ex : Moussa Diallo",
        "idx.contact.form.name_err": "Veuillez entrer votre nom (min. 2 caractères).",
        "idx.contact.form.email": "Adresse e-mail",
        "idx.contact.form.email_ph": "Ex : moussa@ecole.sn",
        "idx.contact.form.email_err": "Veuillez entrer une adresse e-mail valide.",
        "idx.contact.form.subject": "Sujet",
        "idx.contact.form.subject_ph": "Ex : Question sur les bulletins",
        "idx.contact.form.message": "Message",
        "idx.contact.form.message_ph": "Décrivez votre question ou besoin...",
        "idx.contact.form.message_err": "Veuillez entrer un message (min. 10 caractères).",
        "idx.contact.form.submit": "Envoyer le message",
        "idx.contact.form.success": "Message envoyé avec succès ! Nous vous répondrons sous 24h.",
        "idx.contact.form.error": "Une erreur s'est produite. Veuillez réessayer ou nous écrire directement à djangousupportpro@gmail.com.",

        "idx.cta.h2": "Moins de saisie. Plus de temps pour enseigner.",
        "idx.cta.desc": "Rejoignez les enseignants et directeurs qui modernisent leur gestion scolaire.",
        "idx.cta.btn": "Découvrir DJANGOU",

        "idx.footer.desc": "La plateforme EdTech de gestion scolaire conçue pour fonctionner avec ou sans connexion internet.",
        "idx.footer.prod": "Produit",
        "idx.footer.offline": "Mode Hors-ligne",
        "idx.footer.ia": "Intelligence IA",
        "idx.footer.sec": "Sécurité",
        "idx.footer.res": "Ressources",
        "idx.footer.faq": "Questions fréquentes (FAQ)",
        "idx.footer.login": "Connexion",
        "idx.footer.signup": "Inscription",
        "idx.footer.leg": "Légal",
        "idx.footer.priv": "Confidentialité",
        "idx.footer.term": "Conditions d'utilisation",
        "idx.footer.copy": "© 2026 DJANGOU. Tous droits réservés.",
        "idx.footer.prop": "Propulsé par l'innovation EdTech.",

        "idx.js.typewriter": "même sans connexion.",

        "idx.rgpd.text": "<strong>Votre vie privée est importante.</strong> Nous utilisons uniquement les cookies nécessaires au bon fonctionnement de la plateforme (comme le thème sombre).",
        "idx.rgpd.decline": "Continuer sans accepter",
        "idx.rgpd.accept": "J'accepte"
    },
    en: {
        "cs.title": "DJANGOU - Coming Soon",
        "cs.h1_1": "The app is ",
        "cs.h1_2": "almost here.",
        "cs.desc": "The DJANGOU team is preparing the official deployment. The EdTech revolution begins in:",
        "cs.days": "Days",
        "cs.hours": "Hours",
        "cs.minutes": "Minutes",
        "cs.seconds": "Seconds",
        "cs.waitlist.title": "Join the waitlist",
        "cs.waitlist.desc": "Be the first to know when we launch and help us scale the application for your arrival.",
        "cs.placeholder.name": "Your full name",
        "cs.placeholder.email": "Your email address",
        "cs.role.default": "What is your profile?",
        "cs.role.dir": "Principal / School Founder",
        "cs.role.prof": "Teacher / Professor",
        "cs.role.admin": "Administrative Staff",
        "cs.role.parent": "Parent / Student",
        "cs.role.other": "Other",
        "cs.size.default": "School size (Optional)",
        "cs.size.100": "Less than 100 students",
        "cs.size.100_500": "100 to 500 students",
        "cs.size.500": "More than 500 students",
        "cs.size.na": "I don't know / Not applicable",
        "cs.btn.submit": "Notify me at launch",
        "cs.privacy": "Your data will only be used for launch planning.",
        "cs.back": "← Back to home",
        "cs.modal.title": "Thank you for your time and interest in our project!",
        "cs.modal.desc": "Your registration on the waitlist has been recorded. We will contact you as soon as DJANGOU officially launches.",
        "cs.modal.close": "Close",
        "cs.js.sending": "Sending...",
        "cs.js.error": "An error occurred. Please try again.",
        "cs.js.conn_error": "Connection error. Please check your internet.",
        "cs.js.redirect": "Deploying... Redirecting...",

        "idx.title": "DJANGOU - School Management Software",
        "idx.nav.feat": "Features",
        "idx.nav.offline": "Offline",
        "idx.nav.faq": "FAQ",
        "idx.nav.contact": "Contact",
        "idx.aria.theme": "Toggle theme",
        "idx.nav.cta": "Access DJANGOU",

        "idx.hero.eyebrow": "The EdTech platform adapted to your reality",
        "idx.hero.hidden": "Smart and offline school management software.",
        "idx.hero.desc": "DJANGOU automates grade entry, grading, and report card generation. A high-performance application designed for teachers and principals who want to save time.",
        "idx.hero.cta1": "Discover DJANGOU",
        "idx.hero.cta2": "See how it works",
        "idx.hero.chip1": "Real-time AI",
        "idx.hero.chip2": "100% Offline",

        "idx.feat.h2": "Less manual entry. More time to teach.",
        "idx.feat.desc": "Discover how our features rethink school administrative work to eliminate repetitive and time-consuming tasks.",
        "idx.feat.1.h3": "Offline-First",
        "idx.feat.1.p": "Continue working normally even when the internet connection is lost. Automatic synchronization when the network returns.",
        "idx.feat.2.h3": "Smart Voice Dictation",
        "idx.feat.2.p": "Speak your grades out loud. The AI understands them and automatically fills the student table from your phone.",
        "idx.feat.3.h3": "AI Scan and OCR",
        "idx.feat.3.p": "Photograph compatible documents or exams. The AI automatically extracts information to reduce manual entry.",
        "idx.feat.4.h3": "Automated Grading Scales",
        "idx.feat.4.p": "The AI assists you in structuring grading criteria, facilitating automatic and quick calculation of overall averages.",
        "idx.feat.5.h3": "Mass PDF Report Cards",
        "idx.feat.5.p": "Instantly generate professional report cards in PDF format for an entire class with a single click.",
        "idx.feat.6.h3": "Excel Transcripts",
        "idx.feat.6.p": "Easily export complete records and transcripts in Excel format for administration meetings.",

        "idx.ia.eyebrow": "Artificial Intelligence",
        "idx.ia.h2": "Voice dictation: AI at the service of your productivity.",
        "idx.ia.desc": "Enter your grades much faster, even from a smartphone. Activate the microphone, state the student's grade, and DJANGOU associates it with the right row in your digital workbook.",
        "idx.ia.li1": "Reduces the risk of manual entry errors.",
        "idx.ia.li2": "Extremely convenient from a smartphone screen.",
        "idx.ia.demo.voice": "« Martin, 15 out of 20 »",
        "idx.ia.th1": "Student",
        "idx.ia.th2": "Assignment 1",
        "idx.ia.th3": "Status",
        "idx.ia.td.saisi": "Entered",
        "idx.ia.td.voice": "Added by voice",
        "idx.ia.td.waiting": "Waiting",

        "idx.ocr.eyebrow": "Computer Vision",
        "idx.ocr.h2": "Scan and OCR: Digitize in one click.",
        "idx.ocr.desc": "Photograph compatible documents or exams. The AI automatically extracts information to reduce manual entry. An invaluable time saver for processing paper sheets.",
        "idx.ocr.li1": "No more double entry of student lists.",
        "idx.ocr.li2": "Optimized handwriting recognition.",
        "idx.ocr.success": "Extraction successful",

        "idx.off.eyebrow": "Network Resilience",
        "idx.off.h2": "The Offline-First Approach.",
        "idx.off.desc": "In environments where the connection is slow, unstable, or expensive, DJANGOU ensures the continuity of your work. Your recent data is stored locally.",
        "idx.off.badge1": "Offline",
        "idx.off.badge2": "Reconnected",
        "idx.off.step1": "1. You work",
        "idx.off.step1_p": "You enter grades normally.",
        "idx.off.step2": "2. Network cut",
        "idx.off.step2_p": "The application continues to function.",
        "idx.off.step3": "3. Synchronization",
        "idx.off.step3_p": "Back online: automatic sending to the server.",

        "idx.qui.h2": "One platform, two complementary uses.",
        "idx.qui.ens.h3": "For teachers",
        "idx.qui.ens.p": "No more endless manual calculations and double paper-computer entry.",
        "idx.qui.ens.l1": "Less typing thanks to voice",
        "idx.qui.ens.l2": "Automatic average calculation",
        "idx.qui.ens.l3": "Work possible from your phone",
        "idx.qui.adm.h3": "For administration",
        "idx.qui.adm.p": "Centralize school data and generate official documents instantly.",
        "idx.qui.adm.l1": "Global view of classes",
        "idx.qui.adm.l2": "Generation of PDF report cards",
        "idx.qui.adm.l3": "Export of Excel Transcripts",

        "idx.sec.eyebrow": "Security & Trust",
        "idx.sec.h2": "An architecture designed for the protection of your school data.",
        "idx.sec.1.h3": "Cloudflare Infrastructure",
        "idx.sec.1.p": "Active network protection against common attacks and continuous monitoring.",
        "idx.sec.2.h3": "Modern Authentication",
        "idx.sec.2.p": "Integration of secure technologies such as Passkeys to protect accounts.",
        "idx.sec.3.h3": "Secure Synchronization",
        "idx.sec.3.p": "Controlled transfer of data from the offline application to our central servers.",

        "idx.stat.1": "Active teachers",
        "idx.stat.2": "Partner schools",
        "idx.stat.3": "Satisfaction rate",
        "idx.stat.4": "Time saved on data entry",

        "idx.comp.eyebrow": "Transformation",
        "idx.comp.h2": "Before vs After DJANGOU",
        "idx.comp.p": "See concretely what DJANGOU changes in your daily life as a teacher.",
        "idx.comp.sans": "Without DJANGOU",
        "idx.comp.sans.1": "Manual entry grade by grade on paper",
        "idx.comp.sans.2": "Manual average calculations or via Excel",
        "idx.comp.sans.3": "Report cards created one by one taking hours",
        "idx.comp.sans.4": "Loss of work if connection drops",
        "idx.comp.sans.5": "Documents scattered across multiple files",
        "idx.comp.sans.6": "Frequent risk of calculation errors",
        "idx.comp.avec": "With DJANGOU",
        "idx.comp.avec.1": "Grades entered by voice in seconds",
        "idx.comp.avec.2": "Automatic and instant calculations",
        "idx.comp.avec.3": "PDF report cards generated in one click",
        "idx.comp.avec.4": "Continuous work even offline",
        "idx.comp.avec.5": "Everything centralized on a single platform",
        "idx.comp.avec.6": "No calculation errors possible",

        "idx.faq.h2": "Frequently Asked Questions",
        "idx.faq.desc": "Everything you need to know to understand how DJANGOU works.",
        "idx.faq.1.q": "What is DJANGOU?",
        "idx.faq.1.a": "DJANGOU is an EdTech platform designed for the educational world. It helps teachers, principals, and staff manage students, grades, assessments, and report cards faster and more efficiently.",
        "idx.faq.2.q": "Does DJANGOU work without the Internet?",
        "idx.faq.2.a": "Yes. DJANGOU is built on an 'Offline-First' architecture. This means the app continues to work seamlessly during network outages. Data is stored locally and syncs in the background when the connection returns.",
        "idx.faq.3.q": "How does voice dictation work?",
        "idx.faq.3.a": "The application uses Artificial Intelligence to analyze your voice. By simply saying 'Martin, 15 out of 20', the system identifies the student and grade, filling the table automatically and reducing manual entry.",
        "idx.faq.4.q": "How does AI scanning work?",
        "idx.faq.4.a": "By taking a picture of compatible documents or exams, our AI-assisted OCR (Optical Character Recognition) technology extracts relevant texts and numbers to turn them into usable digital data.",
        "idx.faq.5.q": "Can DJANGOU generate report cards?",
        "idx.faq.5.a": "Yes. Once grades and scales are saved, authorized personnel can automatically generate PDF report cards ready to print or send, as well as global Excel transcripts.",
        "idx.faq.6.q": "Can I use DJANGOU on a phone?",
        "idx.faq.6.a": "Absolutely. As a PWA (Progressive Web App), DJANGOU is optimized for smartphones' touch screens, offering a smooth experience without needing a heavy download.",
        "idx.faq.7.q": "Is DJANGOU suitable for entire schools?",
        "idx.faq.7.a": "Yes, DJANGOU is designed for individual teachers as well as global school administration. Principals benefit from centralized tools and data tracking.",
        "idx.faq.8.q": "How do I start with DJANGOU?",
        "idx.faq.8.a": "Simply click on one of the 'Access DJANGOU' buttons on this page. You will be redirected to the main application where you can create your account and set up your classes.",

        "idx.test.eyebrow": "They trust us",
        "idx.test.h2": "Adopted by innovative schools",
        "idx.test.desc": "Discover the upcoming feedback from partner schools that have transformed their administrative management with DJANGOU.",
        "idx.test.1.p": "\"Placeholder for a future testimonial from a school principal detailing the time saved each term.\"",
        "idx.test.1.h4": "Principal, Partner School",
        "idx.test.2.p": "\"Placeholder for a teacher's review on the efficiency of voice dictation and ease of use.\"",
        "idx.test.2.h4": "Lead Teacher",

        "idx.contact.eyebrow": "Contact us",
        "idx.contact.h2": "Have a question? Let's talk.",
        "idx.contact.desc": "Our team is available to answer all your questions about DJANGOU.",
        "idx.contact.disp.h4": "Availability",
        "idx.contact.disp.p": "Mon – Fri, 8am – 6pm (WAT)",
        "idx.contact.badge": "Response usually under 24h",
        "idx.contact.form.name": "Full name",
        "idx.contact.form.name_ph": "E.g. Moussa Diallo",
        "idx.contact.form.name_err": "Please enter your name (min. 2 characters).",
        "idx.contact.form.email": "Email address",
        "idx.contact.form.email_ph": "E.g. moussa@school.sn",
        "idx.contact.form.email_err": "Please enter a valid email address.",
        "idx.contact.form.subject": "Subject",
        "idx.contact.form.subject_ph": "E.g. Question about report cards",
        "idx.contact.form.message": "Message",
        "idx.contact.form.message_ph": "Describe your question or need...",
        "idx.contact.form.message_err": "Please enter a message (min. 10 characters).",
        "idx.contact.form.submit": "Send message",
        "idx.contact.form.success": "Message sent successfully! We will reply within 24h.",
        "idx.contact.form.error": "An error occurred. Please try again or write to us directly at djangousupportpro@gmail.com.",

        "idx.cta.h2": "Less typing. More teaching time.",
        "idx.cta.desc": "Join the teachers and principals who are modernizing their school management.",
        "idx.cta.btn": "Discover DJANGOU",

        "idx.footer.desc": "The EdTech school management platform designed to work with or without an internet connection.",
        "idx.footer.prod": "Product",
        "idx.footer.offline": "Offline Mode",
        "idx.footer.ia": "AI Intelligence",
        "idx.footer.sec": "Security",
        "idx.footer.res": "Resources",
        "idx.footer.faq": "Frequently Asked Questions (FAQ)",
        "idx.footer.login": "Login",
        "idx.footer.signup": "Sign Up",
        "idx.footer.leg": "Legal",
        "idx.footer.priv": "Privacy Policy",
        "idx.footer.term": "Terms of Service",
        "idx.footer.copy": "© 2026 DJANGOU. All rights reserved.",
        "idx.footer.prop": "Powered by EdTech innovation.",

        "idx.js.typewriter": "even offline.",

        "idx.rgpd.text": "<strong>Your privacy is important.</strong> We only use cookies necessary for the platform to function properly (like the dark theme).",
        "idx.rgpd.decline": "Continue without accepting",
        "idx.rgpd.accept": "I accept"
    }
};
"""

with open("i18n-dictionary.js", "w", encoding="utf-8") as f:
    f.write(dict_content)

print("Dictionary written.")
